site_name: ChallengeEU Documentation
theme:
  name: material
  features:
    - content.code.copy
  palette:
    primary: '#571714'
    accent: '#FF6F00'
  font:
    text: 'Alegreya'
    code: 'Fira Code'
  logo: 'assets/images/docsLogo01.svg'
  favicon: 'assets/images/favicon.ico'

extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/extra.js

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html

nav:
  - Home: index.md
  - Branding:
      - Logo: branding/logo.md
      - Colors: branding/colors.md
      - Typography: branding/typography.md
  - Developer Guide:
      - Setup: developer/developer.md
  - WordPress Guide:
      - Forms: wordpress/forms.md
      - Content: wordpress/content.md
      - Staging: wordpress/staging.md