site_name: ChallengeEU Documentation


theme:
  name: material
  # custom_dir: overrides
  palette:
    primary: '#571714'    #  brand color
    accent: '#FF6F00'     # secondary brand color
  font:
    text: 'Alegreya'
    code: 'Fira Code'
  logo: 'images/logo260_80.svg'
  favicon: 'images/favicon.ico'
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascripts/extra.js
  # logo: 'images/logo.png'
  # favicon: 'images/favicon.ico


# Direct Mapping 

nav:
  - Home: index.md
  - Branding:
      - Logo: branding/logo.md
      - Colors: branding/colors.md
      - Typography: branding/typography.md
  - Developer Guide:
      - Setup: developer/developer.md
  - WordPress Guide:
      - Forms: wordpress/forms.md
      - Content: wordpress/content.md
      - Staging: wordpress/staging.md


