site_name: challengeEUDocssss


theme:
  name: material
  palette:
    primary: '#571714'    #  brand color
    accent: '#FF6F00'     # secondary brand color
  font:
    text: 'DM Sans'
    code: 'Fira Code'
  extra_css:
  - css/custom.css
  # logo: 'images/logo.png'
  # favicon: 'images/favicon.ico



nav:
  - Home: index.md
  - Branding:
      - Logo: branding/logo.md
      - Colors: branding/colors.md
      - Typography: branding/typography.md
  - Developer Guide:
      - Setup: developer/setup.md
      - Theme: developer/theme.md
      - Plugins: developer/plugins.md
      - Deployment: developer/deployment.md
  - WordPress Guide:
      - Forms: wordpress/forms.md
      - Content Editing: wordpress/content-editing.md
      - Menus: wordpress/menus.md
  - Project Info:
      - Team: project/team.md
      - Contact: project/contact.md
      - Hosting: project/hosting.md
  - Test Folder:    
      - Team: project/team.md

